version: 2

sphinx:
  configuration: doc/conf.py

python:
    install:
      - requirements: dev_requirements.txt
      - requirements: doc/dev_requirements.txt
      - method: setuptools
        path: .
    system_packages: true

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"