version: 2

sphinx:
  configuration: doc/conf.py

python:
    version: 3.9
    install:
        - requirements: doc/dev_requirements.txt
        - method: pip
          path: .
    system_packages: true

build:
    image: latest