version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - graphviz

sphinx:
  configuration: doc/conf.py
  
formats:
  - pdf

python:
    install:
      - requirements: doc/dev_requirements.txt
      - method: setuptools
        path: .
    system_packages: true
