version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - graphviz
    - libopenmpi-dev

sphinx:
  configuration: doc/conf.py

formats:
  - pdf

python:
    install:
      - requirements: dev_requirements.txt
      - requirements: doc/dev_requirements.txt
      - method: setuptools
        path: .
    system_packages: true
