name: Feature request
description: Suggest a new feature to improve the performance and breadth of FlamingPy
title: '[replace with a short, descriptive title for your request]'
labels: "enhancement"

body:
  - type: checkboxes
    id: terms
    attributes:
      label: |
        Before posting a feature request
      description: |
        Please first search existing GitHub issues and documentation to make sure this request and relevant resolutions do not already exist:
        https://github.com/XanaduAI/ft-stack/issues
      options:
        - label: I have searched existing GitHub issues and documentation to make sure the feature request and relevant resolutions do not already exist.
          required: true
  - type: markdown
    id: description
    attributes:
      value: |
          # Feature description
          A clear and concise description of the desired enhancement. Remember to include references, code snippets, and screenshots below when relevant.
  - type: textarea
    id: details
    attributes:
      label: Feature details
      description: |
        What feature would you like to have?
        Is your feature request related to a problem and/or lack of functionality in FlamingPy?
        How does the new feature improve the performance and/or build on the theory of proposed state-of-the-art methods?
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: |
        Do you have an idea for how this can be implemented and what solution you'd like us to follow? We may ask for your direct contribution here.
        Are there alternative solutions we may want to consider?
  - type: textarea
    id: info
    attributes:
      label: Additional context
      description: |
        Please provide any additional information here.
  - type: dropdown
    id: urgency
    attributes:
      label: How important would you say this feature is?
      options:
        - "1: Not very important. Would be nice to have."
        - "2: Somewhat important. Needed this quarter."
        - "3: Very important! Slowing down or blocking work."
    validations:
      required: true  
