name: Feature request
description: Suggest a new feature to improve the performance and breadth of FlamingPy
title: '[replace with a short, descriptive title for your request]'
labels: "enhancement"

body:
  - type: checkboxes
    id: terms
    attributes:
      label: |
        Before posting a feature request
      description: |
        Please first search existing GitHub issues and documentation to make sure this request and relevant resolutions do not already exist:
        https://github.com/XanaduAI/ft-stack/issues
      options:
        - label: I have searched existing GitHub issues and documentation to make sure the feature request and relevant resolutions do not already exist.
          required: true
- type: markdown
    id: description
    attributes:
      value: |
          # Feature description
          A clear and concise description of the desired enhancement -- remember to include references, code snippets, and screenshots below, if relevant.
  
