name: Create Documentation
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install applications required for building flamingpy docs
      run: sudo apt install -y build-essential graphviz git

    - name: Get the latest pip
      run: python -m pip install --upgrade pip  
 
    - name: Build sphinx documentation
      uses: XanaduAI/sphinx-action@master
      with:
        docs-folder: "doc/"
        pre-build-command: "python -m pip install -r doc/dev_requirements.txt && python setup.py develop"
