name: Create Documentation
on:
  pull_request:
    branches:
      - main

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Build sphinx documentation
      uses: XanaduAI/sphinx-action@master
      with:
        docs-folder: "doc/"
        pre-build-command: "apt install -y build-essential graphviz git && python -m pip install --upgrade pip && python -m pip install -r doc/dev_requirements.txt && python setup.py develop"
