name: Linting Checks
on:
  pull_request:
    branches:    
      - main
      - main-dev

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get the latest pip and pylint
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint
          
      - uses: actions/checkout@v2
      
      - name: Install compilation and testing requirements of flamingpy
        run: python3 -m pip install -r dev_requirements.txt   
        
      - name: Build flamingpy from Source
        run: |
          python setup.py develop 
          python setup.py build_cython --inplace 
          python setup.py build_cmake --inplace  

      - name: Run pylint
        run: python3 -m pylint --disable=R,W flamingpy src/flamingpy/benchmarks/*.py src/flamingpy/examples/*.py tests/unit/*.py
